references:
  working_directory: &working_directory
    working_directory: ~/app

  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/app

  configure_base: &configure_base
    docker:
      - image: node:8

version: 2
jobs:
  checkout:
    <<: *configure_base
    working_directory: ~/repo
    steps:
      - checkout:
      - persist_to_workspace:
          root: .
          paths:
              - 2018

  build-2017:
    <<: *configure_base
    working_directory: ~/repo/2017
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - 2017-dependencies-{{ checksum "yarn.lock" }}
            - 2017-dependencies-

      - run: 
          name: Install and build app
          command: |
              yarn install
              yarn test
              yarn build:prod

      - save_cache:
          paths:
            - node_modules
          key: 2017-dependencies-{{ checksum "yarn.lock" }}

      - persist_to_workspace:
          root: ~/repo
          paths:
              - ./2017/bundle.js
  build-2018:
    <<: *configure_base
    working_directory: ~/repo/2018
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - 2018-dependencies-{{ checksum "yarn.lock" }}
            - 2018-dependencies-

      - run: 
          name: Install and build app
          command: |
              yarn install
              yarn build:prod

      - save_cache:
          paths:
            - node_modules
          key: 2018-dependencies-{{ checksum "yarn.lock" }}

      - persist_to_workspace:
          root: ~/repo
          paths:
              - ./2018/bundle.js

  docs-deploy:
    <<: *configure_base
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ./builds
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@antoineviau.com"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "51:2c:bf:10:3d:c0:16:08:6f:23:ae:79:8e:cb:82:9b"
      - run:
          name: Deploy docs to gh-pages branch
          command: |
            mkdir -p dist/2017 dist/2018
            cp 2017/index.html dist/2017/
            cp builds/2017/bundle.js dist/2017/

            cp 2018/index.html dist/2018/
            cp builds/2018/bundle.js dist/2018/

            touch dist/.nojekyll

            gh-pages --dotfiles --message "[skip ci] Update gh-pages" --dist dist

workflows:
  version: 2
  deploy:
    jobs:
      - checkout:
          filters:
            branches:
              ignore: /gh-pages/
      - build-2018:
          requires:
            - checkout
          filters:
            branches:
              ignore: /gh-pages/
      - build-2017:
          requires:
            - checkout
          filters:
            branches:
              ignore: /gh-pages/
      - docs-deploy:
          requires:
            - build-2017
            - build-2018
          filters:
            branches:
              ignore: /gh-pages/
