references:
  working_directory: &working_directory
    working_directory: ~/app

  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/app

  configure_base: &configure_base
    docker:
      - image: node:8

version: 2
jobs:
  checkout:
    <<: *configure_base
    working_directory: ~/repo
    steps:
      - checkout:
      - persist_to_workspace:
          root: .
          paths:
              - 2018

  build-2018:
    <<: *configure_base
    working_directory: ~/repo/2018
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - 2018-dependencies-{{ checksum "yarn.lock" }}
            - 2018-dependencies-

      - run: 
          name: Install and build app
          command: |
              yarn install
              yarn build:prod
              mkdir 2018
              mv bundle.js 2018/

      - save_cache:
          paths:
            - node_modules
          key: 2018-dependencies-{{ checksum "yarn.lock" }}

      - persist_to_workspace:
          root: ./2018
          paths:
              - ./bundle.js

  docs-deploy:
    <<: *configure_base
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@domain.tld"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "51:2c:bf:10:3d:c0:16:08:6f:23:ae:79:8e:cb:82:9b"
      - run:
          name: Deploy docs to gh-pages branch
          command: |
            ls -al
            ls -al ../
            mkdir dist
            cp 2018/index.html dist/2018
            cp 2018/bundle.js dist/2018
            gh-pages --dotfiles --message "[skip ci] Updates" --dist dist

workflows:
  version: 2
  deploy:
    jobs:
      - checkout
      - build-2018:
          requires:
            - checkout

      - docs-deploy:
          requires:
            - build-2018
